// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavoritesController from "./favorites_controller"
application.register("favorites", FavoritesController)

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import UsersByEmailAuthController from "./users_by_email_auth_controller"
application.register("users-by-email-auth", UsersByEmailAuthController)

import ShareModal from "./share_modal_controller"
application.register("share-modal", ShareModal)

import Property from "./property_controller"
application.register("property", Property)

import ReservationComponent from "./reservation_component_controller"
application.register("reservation-component", ReservationComponent)
