// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./header_controller";
import ModalController from "./modal_controller";
import UsersByEmailAuthController from "./users_by_email_auth_controller";
application.register("header", HelloController);
application.register("modal", ModalController);
application.register("users-by-email-auth", UsersByEmailAuthController)
